In [128]:
import numpy as np
import pandas as pd
import seaborn as sns

In [129]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [130]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [131]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [132]:
df = df[df['species'] != 'setosa']

In [133]:
df.shape

(100, 5)

In [134]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [135]:
df['species'] = df['species'].map({'versicolor':0,'virginica':1})

In [136]:
df.head()

    sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4        0
51           6.4          3.2           4.5          1.5        0
52           6.9          3.1           4.9          1.5        0
53           5.5          2.3           4.0          1.3        0
54           6.5          2.8           4.6          1.5        0

In [137]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [138]:
# Train_Test_Split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.25,random_state = 42)

In [139]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

In [140]:
classifier.fit(X_train, Y_train)

LogisticRegression()

In [141]:
Y_pred = classifier.predict(X_test)

In [142]:
Y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1], dtype=int64)

In [143]:
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(Y_test, Y_pred))

0.92

In [144]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        14
           1       0.91      0.91      0.91        11

    accuracy                           0.92        25
   macro avg       0.92      0.92      0.92        25
weighted avg       0.92      0.92      0.92        25

Multinomial classification

In [145]:
df1 = sns.load_dataset('iris')
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [146]:
df1['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [147]:
df1['species'] = df1['species'].map({'setosa':0,'versicolor':1,'virginica':2})
df1.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [148]:
X = df1.iloc[:,:-1]
Y = df1.iloc[:,-1]

In [149]:
# Train_Test_Split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.25,random_state = 42)

In [150]:
classifier1 = LogisticRegression(multi_class='ovr')

In [151]:
classifier1.fit(X_train, Y_train)

c:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(multi_class='ovr')

In [152]:
Y_pred = classifier1.predict(X_test)

In [153]:
accuracy_score(Y_test, Y_pred)

0.9736842105263158

In [154]:
classification_report(Y_test,Y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        15\n           1       1.00      0.91      0.95        11\n           2       0.92      1.00      0.96        12\n\n    accuracy                           0.97        38\n   macro avg       0.97      0.97      0.97        38\nweighted avg       0.98      0.97      0.97        38\n'

Titanic dataset

In [155]:
df2 = pd.read_csv('titanic.csv')
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [156]:
df2 = df2.drop(columns=['PassengerId','Ticket' ,'Cabin', 'Name'])
df2

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [157]:
df2['Sex'] = df2['Sex'].map({'male':0, 'female':1})
df2

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    0  22.0      1      0   7.2500        S
1           1       1    1  38.0      1      0  71.2833        C
2           1       3    1  26.0      0      0   7.9250        S
3           1       1    1  35.0      1      0  53.1000        S
4           0       3    0  35.0      0      0   8.0500        S
..        ...     ...  ...   ...    ...    ...      ...      ...
886         0       2    0  27.0      0      0  13.0000        S
887         1       1    1  19.0      0      0  30.0000        S
888         0       3    1   NaN      1      2  23.4500        S
889         1       1    0  26.0      0      0  30.0000        C
890         0       3    0  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [158]:
df2['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [159]:
df2.duplicated().sum()

111

In [160]:
df2 = df2.drop_duplicates()
df2.duplicated().sum()

0

In [161]:
df2.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         104
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [162]:
df2 = df2.dropna(subset=['Embarked'])

In [163]:
df2.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         104
SibSp         0
Parch         0
Fare          0
Embarked      0
dtype: int64

In [164]:
df2['Age'].fillna(df2['Age'].mean(), inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_11356\2049159914.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Age'].fillna(df2['Age'].mean(), inplace=True)

In [165]:
df2.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [166]:
df2['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [167]:
df2['Embarked'] = df2['Embarked'].map({'S':0, 'C':1, 'Q':2})
df2

     Survived  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0           0       3    0  22.000000      1      0   7.2500         0
1           1       1    1  38.000000      1      0  71.2833         1
2           1       3    1  26.000000      0      0   7.9250         0
3           1       1    1  35.000000      1      0  53.1000         0
4           0       3    0  35.000000      0      0   8.0500         0
..        ...     ...  ...        ...    ...    ...      ...       ...
885         0       3    1  39.000000      0      5  29.1250         2
887         1       1    1  19.000000      0      0  30.0000         0
888         0       3    1  29.752849      1      2  23.4500         0
889         1       1    0  26.000000      0      0  30.0000         1
890         0       3    0  32.000000      0      0   7.7500         2

[778 rows x 8 columns]

In [168]:
X = df2.iloc[:,1:]
Y = df2.iloc[:,1]

In [169]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=42, test_size=0.2)

In [170]:
classifier2 = LogisticRegression(max_iter=500, solver='liblinear')

In [171]:
classifier2.fit(X_train, Y_train)

LogisticRegression(max_iter=500, solver='liblinear')

In [172]:
Y_pred = classifier2.predict(X_test)

In [173]:
accuracy_score(Y_test, Y_pred)

0.9615384615384616

In [174]:
classification_report(Y_test, Y_pred)

'              precision    recall  f1-score   support\n\n           1       0.97      1.00      0.99        36\n           2       1.00      0.81      0.89        31\n           3       0.95      1.00      0.97        89\n\n    accuracy                           0.96       156\n   macro avg       0.97      0.94      0.95       156\nweighted avg       0.96      0.96      0.96       156\n'

Creating pipeline

In [175]:
from sklearn.pipeline import Pipeline

In [176]:
def clean_data(df):
    df = df.copy()

    df = df.drop(columns=['PassengerId','Ticket' ,'Cabin', 'Name'])

    df = df.dropna(subset=['Embarked'])

    df = df.drop_duplicates()

    df['Embarked'] = df['Embarked'].map({'S':0, 'C':1, 'Q':2})

    df['Sex'] = df['Sex'].map({'male':0, 'female':1})    

    return df

In [177]:
from sklearn.preprocessing import FunctionTransformer

pre_cleaner = FunctionTransformer(clean_data)

In [178]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

fill_na = ColumnTransformer(transformers=[
    ('impute_Age', SimpleImputer(strategy='mean'), ['Age'])
    ],
    remainder='passthrough'
)

In [179]:
preprocessor = Pipeline(steps=[
    ('cleaning',pre_cleaner),
    ('imputer', fill_na),
])

In [180]:
classifier3 = LogisticRegression()

In [182]:
clf = Pipeline([
    ('preprocessing', preprocessor),
    ('classifier', classifier3)
])

In [183]:
df

     sepal_length  sepal_width  petal_length  petal_width  species
50            7.0          3.2           4.7          1.4        0
51            6.4          3.2           4.5          1.5        0
52            6.9          3.1           4.9          1.5        0
53            5.5          2.3           4.0          1.3        0
54            6.5          2.8           4.6          1.5        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        1
146           6.3          2.5           5.0          1.9        1
147           6.5          3.0           5.2          2.0        1
148           6.2          3.4           5.4          2.3        1
149           5.9          3.0           5.1          1.8        1

[100 rows x 5 columns]

In [184]:
df3 = pd.read_csv('titanic.csv')
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [185]:
clf

Pipeline(steps=[('preprocessing',
                 Pipeline(steps=[('cleaning',
                                  FunctionTransformer(func=<function clean_data at 0x000002919AFF0900>)),
                                 ('imputer',
                                  ColumnTransformer(remainder='passthrough',
                                                    transformers=[('impute_Age',
                                                                   SimpleImputer(),
                                                                   ['Age'])]))])),
                ('classifier', LogisticRegression())])

In [186]:
X_train = df3.drop(columns=['Survived'],axis=1)
Y_train = df3['Survived']
clf.fit(X_train, Y_train)

ValueError: Found input variables with inconsistent numbers of samples: [762, 891]